[project]
name = "knee-sarg"
version = "1.0.0"
authors = [{ name = "Matt McCormick" }]
dependencies = [
    "dagster-dbt>=0.25.4",
    "dagster-duckdb-polars>=0.25.3",
    "polars<0.19.6",
    "dagster-duckdb",
    "dagster>=1.9,<2.0",
    "dagster-ssh",
    "datasets",
    "dbt-core",
    "dbt-duckdb",
    "duckdb==1.0.0",
    "huggingface_hub",
    "httpx[http2]",
    "pyarrow",
    "python-slugify",
    "itk>=5.4.0,<6",
    "notebook",
    "dagstermill"
]

requires-python = ">=3.11, <3.13"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
Homepage = "https://radiogenomics.github.io/knee-sarg/"
Changelog = "https://github.com/open-radiogenomics/knee-sarg/commits/main/"
Issues = "https://github.com/open-radiogenomics/knee-sarg/issues"
CI = "https://github.com/open-radiogenomics/knee-sarg/actions"

[project.optional-dependencies]
dev = ["dagster-webserver", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["knee_sarg"]

[tool.setuptools.package-data]
"knee_sarg" = ["../dbt/**"]

[tool.dagster]
module_name = "knee_sarg"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
length-sort = true

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tool.pixi.pypi-dependencies]
knee-sarg = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]
cartilage-thickness = { cmd = "dagster job backfill -j cartilage_thickness_oai_job", description = "Run cartilage thickness backfill job with passed partitions" }
ct-backfill = { cmd = "python scripts/cartilage_thickness_backfill.py", description = "Run cartilage thickness backfill job on given number of partitions" }
clean = { cmd = "rm -rf data/*.duckdb && rm -rf dbt/target dbt/dbt_packages dbt/logs && find data/dagster_home -mindepth 1 ! -name 'dagster.yaml' -delete", description = "Clean the project artifacts" }
jupyter = { cmd = "python scripts/start_jupyter.py", description = "Run jupyter notebook" }
collect-images = { cmd = "dagster asset materialize --select collected_images_oai -m knee_sarg", description = "Materialize collected_images asset" }

[tool.pixi.feature.dev.tasks]
dev = { cmd = "dagster dev -v", description = "Run the development environment" }
lint = { cmd = "ruff check .", description = "Run ruff to check linting issues" }
fix = { cmd = "ruff check . --fix", description = "Run ruff to fix linting issues" }
format = { cmd = "ruff format", description = "Run ruff to format code" }
check-format = { cmd = "ruff format --check", description = "Run ruff to check code formating" }

